version: 0.2

phases:
  install:
    commands:
      - apt-get install -y maven
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-southeast-1)
  build:
    commands:
      - mvn package
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t myrepo:latest .
      - docker tag myrepo:latest 139379777393.dkr.ecr.ap-southeast-1.amazonaws.com/myrepo:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 139379777393.dkr.ecr.ap-southeast-1.amazonaws.com/myrepo:latest